# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d9d037a2ea816a9b76333bebd32405188a945e38d586b36a9ab56e5f2aec72546ea7dccfd01f2119448c44f37b738365997bfdf6a457cb8d50251063769a8c4

test:
  secret_key_base: 529dcfe49a10028caf9e6a7b820c332b1ae33b589bff89d6312217405da9084bbcac6bbf63b38fa323a665ef39fdce077916398bd081758686866901d33a8c23

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
